### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by akimokh** [hollaus/TinyPlanetMaker#1]
Hi There,  i followed all the steps but unfortunately i got an error :  Configuration with name 'default' not found 

plus this one :   

**throw new GradleException("NDK location not found. Define location with ndk.dir in the local.properties file or with an ANDROID_NDK_ROOT environment variable.")**

Can you please help ?   thank you :) 👍 

apply plugin: 'com.android.application'

android {
    signingConfigs {
        config2 {
            keyAlias 'xxx'
            keyPassword 'xxx'
            storeFile file('test.jks')
            storePassword 'xxx'
        }
    }
    compileSdkVersion 23
    buildToolsVersion '23.0.2'
    defaultConfig {
        applicationId "org.hofapps.tinyplanet"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 3
        versionName "1.1"
    }
    // begin
    sourceSets.main {
        jni.srcDirs = [] //disable automatic nd k-build call
    }
    task ndkBuild(type: Exec) {
        workingDir file('src/main')
        commandLine getNdkBuildCmd()
    }

    task cleanNative(type: Exec, description: 'Clean JNI object files') {
        commandLine getNdkBuildCmd(),
                '-C', file('src/main/jni').absolutePath, // Change src/main/jni the relative path to your jni source
                'clean'
    }

    clean.dependsOn 'cleanNative'

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn ndkBuild
    }
    //end
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config2
        }
        debug {
            signingConfig signingConfigs.config2
        }
    }
    productFlavors {
    }

}

def getNdkDir() {
    if (System.env.ANDROID_NDK_ROOT != null)
        return System.env.ANDROID_NDK_ROOT

    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    def ndkdir = properties.getProperty('ndk.dir', null)
    if (ndkdir == null)
        throw new GradleException("NDK location not found. Define location with ndk.dir in the local.properties file or with an ANDROID_NDK_ROOT environment variable.")

    return ndkdir
}

def getNdkBuildCmd() {
    def ndkbuild = getNdkDir() + "/ndk-build"
    // TODO: check why we cannot include package Os:
//    if (Os.isFamily(Os.FAMILY_WINDOWS))
    ndkbuild += ".cmd"

    return ndkbuild
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'
    compile project(':openCVLibrary310')

}

**Comment by hollaus** [comment]
Hi,
sorry for the late reply. Have you set the Android NDK location correctly?

**Comment by hollaus** [comment]
I could not reproduce the issue on a fresh Android Studio installation, I guess the NDK path was not set correctly. The readme was updated and simplified to point out the main steps
